In [1]:
import pandas as pd
import datetime
from dateutil.relativedelta import relativedelta
import numpy as np
import math
import datetime
import statsmodels.api as sm
from rpy2.robjects.packages import importr
from rpy2.rinterface import RRuntimeError
from rpy2.rinterface import NARealType
import rpy2.robjects as ro
from rpy2.robjects import pandas2ri
import numpy as np
import scipy as sp
from sklearn import linear_model
from yahoo_finance import Share
import pandas_datareader as web
from pandas.tseries.offsets import BDay
from matplotlib.dates import DateFormatter, WeekdayLocator,    DayLocator, MONDAY
from matplotlib.finance import candlestick_ohlc
import pickle
import os
##################################################################################################################

r_forecast = importr("forecast")
stats = importr('stats')
tseries = importr('tseries')
pandas2ri.activate()
r_forecast_obj = importr("DemandForecasting")

/usr/local/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
/usr/local/lib/python3.6/site-packages/matplotlib/cbook.py:136: MatplotlibDeprecationWarning: The finance module has been deprecated in mpl 2.0 and will be removed in mpl 2.2. Please use the module mpl_finance instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)

In [2]:
raw_data_folder = "/Users/dimbul/Desktop/private/stock_Prediction/raw_data/"
output_folder = "/Users/dimbul/Desktop/private/stock_Prediction/output_data/"
Company_Name = "Tesla"
Company_Code = "TSLA"
start = datetime.datetime(2016,1,1)
end = datetime.date.today()
start_date_str = start.strftime("%m%d%Y")
end_date_str = end.strftime("%m%d%Y")

In [5]:
file_path = raw_data_folder + Company_Name +"_" + start_date_str + "_" +"Stock_Data.csv"
today_date = datetime.datetime.today()

if os.path.isfile(file_path):
    csv_data = pd.read_csv(file_path)
    csv_data.index = pd.to_datetime(csv_data['Date'])
    del csv_data['Date']
    end_time = max(csv_data.index)
    query_start_date = datetime.datetime.strptime((end_time + datetime.timedelta(days=1)).strftime('%Y-%m-%d'),"%Y-%m-%d")
    query_end_date = today_date
    new_data = web.DataReader(Company_Code,"yahoo",query_start_date,query_end_date)
    temp_data = pd.concat([csv_data,new_data])
    stock_data = temp_data.groupby(temp_data.index).first()    
else:
    stock_data = web.DataReader(Company_Code, "yahoo", start, end)

stock_data.to_csv(file_path)

In [6]:
stock_data

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2016-01-04,230.720001,231.380005,219.000000,223.410004,223.410004,6827100
2016-01-05,226.360001,226.889999,220.000000,223.429993,223.429993,3186800
2016-01-06,220.000000,220.050003,215.979996,219.039993,219.039993,3779100
2016-01-07,214.190002,218.440002,213.669998,215.649994,215.649994,3554300
2016-01-08,217.860001,220.440002,210.770004,211.000000,211.000000,3628100
2016-01-11,214.009995,214.449997,203.000000,207.850006,207.850006,4089700
2016-01-12,211.600006,213.740005,205.309998,209.970001,209.970001,3091900
2016-01-13,212.009995,212.649994,200.000000,200.309998,200.309998,4126400
2016-01-14,202.210007,210.000000,193.380005,206.179993,206.179993,6490700
2016-01-15,198.970001,205.070007,197.250000,204.990005,204.990005,5578600
2016-01-19,208.710007,210.470001,200.779999,204.720001,204.720001,4038700
2016-01-20,199.399994,201.279999,191.250000,198.699997,198.699997,5838600
2016-01-21,201.550003,203.229996,195.020004,199.970001,199.970001,3166200
2016-01-22,204.800003,205.500000,199.029999,202.550003,202.550003,3124100
2016-01-25,200.059998,203.570007,195.880005,196.380005,196.380005,2698700
2016-01-26,196.699997,197.820007,188.880005,193.559998,193.559998,4946800
2016-01-27,192.380005,193.259995,185.770004,188.070007,188.070007,3617200
2016-01-28,190.789993,191.279999,182.410004,189.699997,189.699997,4592800
2016-01-29,189.949997,193.740005,188.080002,191.199997,191.199997,2852300
2016-02-01,188.759995,199.520004,182.750000,196.940002,196.940002,5297600
2016-02-02,192.419998,193.119995,180.229996,182.779999,182.779999,5773600
2016-02-03,183.589996,183.940002,170.179993,173.479996,173.479996,7931400
2016-02-04,170.699997,175.979996,166.990005,175.330002,175.330002,4363900
2016-02-05,171.300003,173.000000,157.740005,162.600006,162.600006,9437600
2016-02-08,157.100006,157.149994,146.000000,147.990005,147.990005,9313000
2016-02-09,142.320007,159.789993,141.050003,148.250000,148.250000,8575100
2016-02-10,150.500000,154.970001,141.740005,143.669998,143.669998,10406500
2016-02-11,152.000000,163.259995,147.000000,150.470001,150.470001,14252400
2016-02-12,155.000000,157.009995,143.699997,151.039993,151.039993,7235800
2016-02-16,158.699997,162.949997,154.110001,155.169998,155.169998,5593800
...,...,...,...,...,...,...
2017-08-11,356.970001,361.260010,353.619995,357.869995,357.869995,4365800
2017-08-14,364.630005,367.660004,362.600006,363.799988,363.799988,4502700
2017-08-15,365.200012,365.489990,359.369995,362.329987,362.329987,3085100
2017-08-16,363.000000,366.500000,362.519989,362.910004,362.910004,3413800
2017-08-17,361.209991,363.299988,351.589996,351.920013,351.920013,5027700
2017-08-18,352.910004,354.000000,345.799988,347.459991,347.459991,5408200
2017-08-21,345.820007,345.820007,331.850006,337.859985,337.859985,6495400
2017-08-22,341.130005,342.239990,337.369995,341.350006,341.350006,4322000
2017-08-23,338.989990,353.489990,338.299988,352.769989,352.769989,4954500
2017-08-24,352.519989,356.660004,349.739990,352.929993,352.929993,4584700
2017-08-25,354.239990,355.690002,347.299988,348.049988,348.049988,3484000
2017-08-28,347.279999,347.350006,339.720001,345.660004,345.660004,3764000
2017-08-29,339.480011,349.049988,338.750000,347.359985,347.359985,4073700
2017-08-30,349.670013,353.470001,347.000000,353.179993,353.179993,3412900
2017-08-31,353.549988,358.440002,352.820007,355.899994,355.899994,4072800
2017-09-01,356.119995,357.589996,353.690002,355.399994,355.399994,3049500
2017-09-05,353.799988,355.489990,345.890015,349.589996,349.589996,3835100
2017-09-06,349.500000,350.980011,341.559998,344.529999,344.529999,4091400
2017-09-07,345.980011,352.480011,343.450012,350.609985,350.609985,4239200
2017-09-08,348.989990,349.779999,342.299988,343.399994,343.399994,3257600
2017-09-11,351.350006,363.709991,350.000000,363.690002,363.690002,7667100
2017-09-12,364.489990,368.760010,360.399994,362.750000,362.750000,5972900
2017-09-13,363.820007,368.070007,359.589996,366.230011,366.230011,4185200
2017-09-14,364.329987,377.959991,362.630005,377.640015,377.640015,7202500
2017-09-15,374.510010,380.000000,372.700012,379.809998,379.809998,5420500
2017-09-18,380.250000,389.609985,377.679993,385.000000,385.000000,7188000
2017-09-19,380.000000,382.390015,373.570007,375.100006,375.100006,6451900
2017-09-20,373.000000,378.250000,371.070007,373.910004,373.910004,4919100
2017-09-21,374.899994,376.829987,364.510010,366.480011,366.480011,4618200
2017-09-22,366.489990,369.899994,350.880005,351.089996,351.089996,8119800

In [ ]:



##################################################################################################################

regress = linear_model.LinearRegression(fit_intercept=True)
failed_combination={}




##################################################################################################################

print("Testing......")


##################################################################################################################

list_columns = ["Close","Open","High","Low"]
#Number of Business Days to be forecasted. 
Forecasting_horizon=6


final_output = {Company_Name:{}}

In [ ]:
##################################################################################################################
def pandas_candlestick_ohlc(dat, stick = "day", otherseries = None):
    """
    :param dat: pandas DataFrame object with datetime64 index, and float columns "Open", "High", "Low", and "Close", likely created via DataReader from "yahoo"
    :param stick: A string or number indicating the period of time covered by a single candlestick. Valid string inputs include "day", "week", "month", and "year", ("day" default), and any numeric input indicates the number of trading days included in a period
    :param otherseries: An iterable that will be coerced into a list, containing the columns of dat that hold other series to be plotted as lines
 
    This will show a Japanese candlestick plot for stock data stored in dat, also plotting other series if passed.
    """
    mondays = WeekdayLocator(MONDAY)        # major ticks on the mondays
    alldays = DayLocator()              # minor ticks on the days
    dayFormatter = DateFormatter('%d')      # e.g., 12
 
    # Create a new DataFrame which includes OHLC data for each period specified by stick input
    transdat = dat.loc[:,["Open", "High", "Low", "Close"]]
    if (type(stick) == str):
        if stick == "day":
            plotdat = transdat
            stick = 1 # Used for plotting
        elif stick in ["week", "month", "year"]:
            if stick == "week":
                transdat["week"] = pd.to_datetime(transdat.index).map(lambda x: x.isocalendar()[1]) # Identify weeks
            elif stick == "month":
                transdat["month"] = pd.to_datetime(transdat.index).map(lambda x: x.month) # Identify months
            transdat["year"] = pd.to_datetime(transdat.index).map(lambda x: x.isocalendar()[0]) # Identify years
            grouped = transdat.groupby(list(set(["year",stick]))) # Group by year and other appropriate variable
            plotdat = pd.DataFrame({"Open": [], "High": [], "Low": [], "Close": []}) # Create empty data frame containing what will be plotted
            for name, group in grouped:
                plotdat = plotdat.append(pd.DataFrame({"Open": group.iloc[0,0],
                                            "High": max(group.High),
                                            "Low": min(group.Low),
                                            "Close": group.iloc[-1,3]},
                                           index = [group.index[0]]))
            if stick == "week": stick = 5
            elif stick == "month": stick = 30
            elif stick == "year": stick = 365
 
    elif (type(stick) == int and stick >= 1):
        transdat["stick"] = [np.floor(i / stick) for i in range(len(transdat.index))]
        grouped = transdat.groupby("stick")
        plotdat = pd.DataFrame({"Open": [], "High": [], "Low": [], "Close": []}) # Create empty data frame containing what will be plotted
        for name, group in grouped:
            plotdat = plotdat.append(pd.DataFrame({"Open": group.iloc[0,0],
                                        "High": max(group.High),
                                        "Low": min(group.Low),
                                        "Close": group.iloc[-1,3]},
                                       index = [group.index[0]]))
 
    else:
        raise ValueError('Valid inputs to argument "stick" include the strings "day", "week", "month", "year", or a positive integer')
 
 
    # Set plot parameters, including the axis object ax used for plotting
    fig, ax = plt.subplots()
    fig.subplots_adjust(bottom=0.2)
    if plotdat.index[-1] - plotdat.index[0] < pd.Timedelta('730 days'):
        weekFormatter = DateFormatter('%b %d')  # e.g., Jan 12
        ax.xaxis.set_major_locator(mondays)
        ax.xaxis.set_minor_locator(alldays)
    else:
        weekFormatter = DateFormatter('%b %d, %Y')
    ax.xaxis.set_major_formatter(weekFormatter)
 
    ax.grid(True)
 
    # Create the candelstick chart
    candlestick_ohlc(ax, list(zip(list(date2num(plotdat.index.tolist())), plotdat["Open"].tolist(), plotdat["High"].tolist(),
                      plotdat["Low"].tolist(), plotdat["Close"].tolist())),
                      colorup = "black", colordown = "red", width = stick * .4)
 
    # Plot other series (such as moving averages) as lines
    if otherseries != None:
        if type(otherseries) != list:
            otherseries = [otherseries]
        dat.loc[:,otherseries].plot(ax = ax, lw = 1.3, grid = True)
 
    ax.xaxis_date()
    ax.autoscale_view()
    plt.setp(plt.gca().get_xticklabels(), rotation=45, horizontalalignment='right')
 
    plt.show()

In [ ]:
import matplotlib.pyplot as plt   # Import matplotlib
# This line is necessary for the plot to appear in a Jupyter notebook
%matplotlib inline
# Control the default size of figures in this Jupyter notebook
%pylab inline
pylab.rcParams['figure.figsize'] = (15, 9)   # Change the size of plots
 

stock_data["Open"].plot()

In [ ]:

for typeof in list_columns:
    print("typeof")
    print(typeof)
    final_output[Company_Name][typeof] = {}
    comb_df = stock_data[[typeof]]
    comb_df['Time_Line']= comb_df.index
    comb_df=comb_df.rename(columns={typeof:'Frequency'})
    comb_df=comb_df.reset_index(drop=True)
    comb_df['index']=comb_df.index
    comb_df['Year']=comb_df.Time_Line.dt.year
    comb_df['month']=comb_df.Time_Line.dt.month

    ##############
    # This is were the pandas dataframe is converted into 'r' object. 
    r_skill_print_freq = pandas2ri.py2ri(comb_df)
    # Forecasting_horizon let you forecast from the end_date  till end_date + Forecasting_horizon. 
    

    r_prediction_period = ro.IntVector([Forecasting_horizon])


    # In[112]:


    r_forecasted_values_stl = r_forecast_obj.hcl_forecasting_stl(r_skill_print_freq, r_prediction_period)
    forecasted_values_stl = r_forecasted_values_stl.rx()
    r_forecasted_values = list(forecasted_values_stl[8])
    for n_temp in range(0,Forecasting_horizon):
        r_forecasted_values.append(forecasted_values_stl[3][n_temp])
    for temp_n in range(0,len(r_forecasted_values)):
        if r_forecasted_values[temp_n] <0:
            r_forecasted_values[temp_n] = 0 




    ##########

    #Total number of actual Data points 
    length_actual= comb_df.shape[0]
    # Total Length of Forecasted values. 
    length_forecast = len(r_forecasted_values)
    # Total Length of predictions. 
    no_of_predictions=length_forecast

    rng = pd.date_range(start, periods=no_of_predictions, freq='M')
    ts = rng.to_period()
    rng = ts.to_timestamp()


    actual_time_series = pd.Series(np.array(comb_df.Frequency), index=comb_df.Time_Line)
    pred_time_series = pd.Series(np.array(r_forecasted_values), index=rng)


    error = comb_df.Frequency[3:] - r_forecasted_values[3:length_actual]


    MAPE = np.abs(error/comb_df.Frequency[3:])
    MAPE = np.mean(MAPE) 
    Uncertainity_measurement = []
    Error_variance = np.var(error)
    for i_temp in range(0,Forecasting_horizon):
        Uncertainity_measurement.append(np.sqrt((i_temp+1)*Error_variance))

    actual_df = actual_time_series.to_frame()
    actual_df.columns = ["Actual"]
    time_indices = actual_df.index


    forecast_time_list = []
    for i in range(1,Forecasting_horizon+1):
        forecast_time_list +=[end+BDay(i)]
        


    forecast_DatetimeIndex = pd.DatetimeIndex(forecast_time_list)



    final_forecast_DTIndex = time_indices.append(forecast_DatetimeIndex)



    forecasted_df = pd.DataFrame(data={"Forecasted": r_forecasted_values} , index=final_forecast_DTIndex)


    final_combine_data = pd.concat([actual_df,forecasted_df], axis=1)
 
    final_output[Company_Name][typeof]["Forecast"] = final_combine_data.to_dict()
    final_output[Company_Name][typeof]["MAPE"] = MAPE
    final_output[Company_Name][typeof]["uncertainity"] = Uncertainity_measurement
    final_output[Company_Name]["Forecast_Horizon"] = Forecasting_horizon
    final_output[Company_Name]["start_date"] = start
    final_output[Company_Name]["end_date"] = end
    final_output[Company_Name]["Company_Code"] = Company_Code

In [ ]:
#final_output.keys()
#final_output['Tesla'].keys()
#final_output['Tesla']['Open'].keys()
#high_tesla_forecast =pd.DataFrame(final_output['Tesla']['High']['Forecast']) # [-12:]
#high_tesla_forecast['Error']=high_tesla_forecast["Forecasted"] - high_tesla_forecast["Actual"]

In [ ]:
final_data = {"_Source":final_output}

In [ ]:
#Writing Pickle file 
with open(output_folder+Company_Name+"_Forecast_"+datetime.datetime.today().strftime("%m_%d_%Y")+".pkl",'wb') as fp:
    pickle.dump(final_data,fp)

In [ ]:
#Reading Pickle File 
with open(output_folder+Company_Name+"_Forecast_"+datetime.datetime.today().strftime("%m_%d_%Y")+".pkl",'rb') as fp:
    dummy_var = pickle.load(fp)

In [ ]:
# For Displaying Data
pd.DataFrame(dummy_var["_Source"][Company_Name]['Open']['Forecast'])[:12]

In [ ]:
# For Displaying last six Data points
pd.DataFrame(dummy_var["_Source"][Company_Name]['Close']['Forecast'])[-6:]

# For Displaying first six Data points
#pd.DataFrame(dummy_var["_Source"][Company_Name]['Close']['Forecast'])[:6]

In [ ]:
# For Displaying Data
pd.DataFrame(dummy_var["_Source"][Company_Name]['High']['Forecast'])[-6:]

In [ ]:
# For Displaying Data
pd.DataFrame(dummy_var["_Source"][Company_Name]['Low']['Forecast'])[-4:]

In [ ]:
close_forecast = pd.DataFrame(final_output[Company_Name]["Close"]["Forecast"])
close_forecast.columns = ["Close_Actual","Close_Forecast"]
open_forecast = pd.DataFrame(final_output[Company_Name]["Open"]["Forecast"])
open_forecast.columns = ["Open_Actual","Open_Forecast"]
high_forecast = pd.DataFrame(final_output[Company_Name]["High"]["Forecast"])
high_forecast.columns = ["High_Actual","High_Forecast"]
low_forecast = pd.DataFrame(final_output[Company_Name]["Low"]["Forecast"])
low_forecast.columns = ["Low_Actual","Low_Forecast"]

In [ ]:
all_data = pd.concat([open_forecast,close_forecast,high_forecast,low_forecast],axis=1)

In [ ]:
forecast_all_data = all_data[["Open_Forecast","Close_Forecast","High_Forecast","Low_Forecast"]]
forecast_all_data.columns =  ["Open","Close","High","Low"]

In [ ]:
# Plotting Candle Plot for forecasted Data 
pandas_candlestick_ohlc(forecast_all_data[-Forecasting_horizon:])